### ISSUE TITLE
pyproject.toml extras not working

### ISSUE THREAD

**Issue by jembishop** [conda/conda-lock#294]
```
conda-lock, version 1.3.0
Ubuntu 22.04
```

Hi I have a `pyproject.toml` file like this:

```toml
[tool.poetry]
name = "python-env"
version = "0.1.0"
description = "none"
authors = ["Author <poetry@wantsemail.com>"]

[tool.poetry.dependencies]
python = "3.8.*"
addict = "2.4.0"

[tool.poetry.extras]
test = ["pytest"]
boris = ["numpy==1.22.2"]

[tool.conda-lock]
channels = ['conda-forge', 'defaults', 'pip']
platforms = [
    'linux-64'
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

However when I run `conda-lock  -f pyproject.toml --log-level DEBUG -p linux-64 --extras boris`
It doesn't seem to generate a lock file with any of the extras at all. 

Looking at the code I am a bit confused how this even can work as it looks like in
https://github.com/conda-incubator/conda-lock/blob/main/conda_lock/src_parser/pyproject_toml.py#L98

The extras are not even added to the dependencies, but possibly something I am missing. 

Thanks
