### ISSUE TITLE
pip-integration: conda-lock fails to resolve open3d (potential vendored poetry issue)

### ISSUE THREAD

**Issue by mjlbach** [conda/conda-lock#395]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

`conda-lock lock --micromamba --file env.yml -p linux-64`

```yaml
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - open3d
```

yields a failure because

```
(Pdb) pp env.supported_tags                     
[<cp38-cp38-manylinux_2_17_x86_64 @ 140111826615936>,
 <cp38-cp38-manylinux2014_x86_64 @ 140111826614848>,
 <cp38-cp38-manylinux2010_x86_64 @ 140111826614912>,
 <cp38-cp38-manylinux1_x86_64 @ 140111826614720>,
```

does not intersect with
```
(Pdb) pp self.tags
{<cp38-cp38-manylinux_2_27_x86_64 @ 140111824719744>}
```

in `conda_lock/_vendor/poetry/installation/chooser.py:choose_for`
