### ISSUE TITLE
Validate that an input hash matches current sources

### ISSUE THREAD

**Issue by MattF-NSIDC** [conda/conda-lock#479]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

I'd like to be able to validate that a lock file has been created from the current source specifiction's contents. So for example, if someone changes `environment.yml` and opens a PR, my CI could very quickly catch that the lockfile wasn't updated by re-calculating a hash and comparing it to `content_hash` in the lockfile.

`conda-lock lock --check-input-hash` is very close to what I want to do, with the downside that instead of failing immediately if the hash validation fails, it will solve the environment and update the lockfile. What about a `--check-input-hash-without-solve` or similar flag for this behavior?

### Why is this needed?

This helps projects automatically catch and _quickly_ prompt (by e.g. failing CI job or bot comment) contributors who have forgotten to lock the environment after changing it. [This](https://github.com/CryoInTheCloud/hub-image/pull/78) `repo2docker`-based project, for example, expects users to manually update their lockfile or use `/condalock` in a PR comment to trigger a bot to update the lock file, but they have to _remember_ to do that!

### What should happen?

On running some command like `conda-lock ensure-sources` or `conda-lock lock --check-input-hash-without-solve`:

1. Calculate a new `content_hash` from sources in `conda-lock.yml`
2. Does it match `content_hash` in `conda-lock.yml`?
3. If yes, exit `0`, if no exit non-zero

No solve or write to a file should occur at any time.

### Additional Context

I apologize if this has been asked already! Tried to find it and came up empty.

**Comment by MattF-NSIDC** [comment]
This feels like a "good first issue". I'd like to take a stab at it this weekend :)

**Comment by maresb** [comment]
Hi @MattF-NSIDC, great to hear from you again! This seems fairly straightforward, and I have no objection, but be warned that `content_hash` may disappear soon. Please see the discussion in #432.

**Comment by MattF-NSIDC** [comment]
Hey Ben, likewise :)

Do you expect that change will come with a version increment of the unified lock file format? I also think it would be a valuable to retain support for this validation functionality by enabling `conda-lock` to continue to output and operate on version `1` unified lockfiles!

**Comment by maresb** [comment]
Yes, we will definitely have a version increment and a transition period.

**Comment by MattF-NSIDC** [comment]
Wonderful.

Do you think [this](https://github.com/conda/conda-lock/issues/432#issuecomment-1587672643) suggestion (your [pseudocode](https://github.com/conda/conda-lock/issues/432#issuecomment-1637071282)) are in-scope for a new `conda-lock` feature? This would address the same problem, but better IMO. Your point about equivalent but unequal specifications was a good one.

**Comment by maresb** [comment]
That would absolutely be in-scope for a new conda-lock feature! Would you be interested in tackling this? (I'd really like to do it myself, but I'm really time-constrained at the moment, so I'd be really grateful for any help!)

**Comment by MattF-NSIDC** [comment]
I'm going to try and give it a shot this weekend, will let you know whether I'm able to work it in or not! You may see a PR from my personal account @mfisher87 (I continue to regret having two GitHub accounts!)

**Comment by maresb** [comment]
That's wonderful!!!

If along the way you find tangential things that you want to improve / document, please be bold and don't hold back.

For code review, I greatly prefer lots of smaller commits rather than one monolith, if you can manage it.

**Comment by MattF-NSIDC** [comment]
>For code review, I greatly prefer lots of smaller commits rather than one monolith, if you can manage it.

No problem :)

**Comment by mfisher87** [comment]
I've been using this feature as a learning opportunity for some friends who are new to Python and open-source (and for myself to learn about the conda-lock code). We started with implementing the "check input hashes and exit" approach because it was a quicker path to victory, and didn't quite nail it down in our limited session this weekend. We'll probably get it next weekend and move on to the "check for agreement" approach. I was thinking we could submit them each as separate pull requests, and reject one of them if needed.

If someone else wants to implement any of this, we won't be offended if you don't wait for us. We're just in it for learning :)

**Comment by Adam-D-Lewis** [comment]
I'd be interested in working on this.  When I started to look into this, I did come across something which seemed strange, but might be expected.  When processing lockfiles I've found they can sometimes contain a dependency twice, once with `manager: pip` and another with `manager: conda`.  I take it this is expected.  In this case, I assume the pip managed entry takes precedence.  Under the hood, what I expect is happening is all the conda managed dependencies are installed and then the pip dependencies are installed afterwards which is why they take precedence in the final environment.

When I'm checking if environment spec is satisfied by the lockfile (as explained in https://github.com/conda/conda-lock/issues/432#issuecomment-1637071282), in the case a package is listed twice, would it be sufficient to only check the pypi managed version or would it be better to check all the conda managed env spec against the conda managed parts of the lockfile and separately check the pip managed parts of the env spec with the conda managed parts of the env-spec.  I say this as the conda and pip dependencies in the lockfile can list different versions.

E.g. when I run `conda-lock -f pyproject.toml -p linux-64 --lockfile conda-lock.yml` on this file
```toml
# pyproject.toml
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
mailgun = { version = "*", source = "pypi" }  # only depends on requests
requests = "<2.32"

[tool.conda-lock]
channels = ['conda-forge']
platforms = ['linux-64']
```

I get a lockfile with
```yaml
# conda-lock.yml
- name: requests
  version: 2.31.0
  manager: conda
  platform: linux-64
  dependencies:
    certifi: '>=2017.4.17'
    charset-normalizer: '>=2,<4'
    idna: '>=2.5,<4'
    python: '>=3.7'
    urllib3: '>=1.21.1,<3'
  url: https://conda.anaconda.org/conda-forge/noarch/requests-2.31.0-pyhd8ed1ab_0.conda
  hash:
    md5: a30144e4156cdbb236f99ebb49828f8b
    sha256: 9f629d6fd3c8ac5f2a198639fe7af87c4db2ac9235279164bfe0fcb49d8c4bad
  category: main
  optional: false
- name: requests
  version: 2.32.4  # <---- different than 2.31.0 above
  manager: pip
  platform: linux-64
  dependencies:
    certifi: '>=2017.4.17'
    charset-normalizer: '>=2,<4'
    idna: '>=2.5,<4'
    urllib3: '>=1.21.1,<3'
  url: https://files.pythonhosted.org/packages/7c/e4/56027c4a6b4ae70ca9de302488c5ca95ad4a39e190093d6c1a8ace08341b/requests-2.32.4-py3-none-any.whl
  hash:
    sha256: 27babd3cda2a6d50b30443204ee89830707d396671944c998b5975b031ac2b2c
  category: main
  optional: false
...
```
