### ISSUE TITLE
conda-lock fails to respect non-default git branch/ref/rev from poetry `pyproject.toml`

### ISSUE THREAD

**Issue by cameronraysmith** [conda/conda-lock#568]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

On

```sh
❯ conda-lock --version  
conda-lock, version 2.5.2.dev12+g0481cc6
```

if I specify any

<details><summary>ONE of branch or rev</summary>
<p>

```toml
[tool.poetry.dependencies]
# Other dependencies...

flytekit = { git = "https://github.com/cameronraysmith/flytekit.git", rev = "b1e64ba20f1ddd83723e455d2bf893d8f3fc84b7" }
flytekit = { git = "https://github.com/cameronraysmith/flytekit.git", branch = "3928-pandas-2" }
```

</p>
</details> 

other than the default branch HEAD in the dependencies and run conda-lock

```sh
❯ poe -d conda-lock
Poe => conda-lock --conda mamba --kind lock --kind env --no-dev-dependencies --filter-categories --category workflows --virtual-package-spec environments/conda/virtual-packages.yml --filename-template 'environments/conda/conda-{platform}.lock' --lockfile environments/conda/conda-lock.yml -f pyproject.toml
```

<details><summary>with virtual-packages.yml,</summary>
<p>

```yaml
subdirs:
  linux-64:
    packages:
      __cuda: 12.3.0
      __glibc: 2.35
```

</p>
</details> 

then 

* for the case of specifying a commit sha as rev, I get an error stating that conda-lock cannot checkout the default branch even though the commit sha is not part of that branch

```pytb
    raise CalledProcessError(
conda_lock._vendor.poetry.utils._compat.CalledProcessError: Command '['git', '--git-dir', '/var/folders/zx/66kfpxbj16n3blcbnn1kys9h0000gp/T/pypoetry-git-flytekitj9ytruxm/.git', '--work-tree', '/var/folders/zx/66kfpxbj16n3blcbnn1kys9h0000gp/T/pypoetry-git-flytekitj9ytruxm', 'checkout', 'master']' returned non-zero exit status 1.
```

* or, if I specify a non-default branch, the commit sha that is placed in the conda-lock output is the HEAD of the default branch having ignored the constraint pointing to a non-default branch or sha that is not part of the default branch history.

This also holds true if I place all the dependencies 

<details><summary>inside the conda-lock dependencies table.</summary>
<p>

```toml
[tool.conda-lock.dependencies]
flytekit = { git = "https://github.com/cameronraysmith/flytekit.git", branch = "3928-pandas-2" }
```

</p>
</details> 

In all cases, the

<details><summary>correct sha appears in the poetry.lock file.</summary>
<p>

```toml
[package.source]
type = "git"
url = "https://github.com/cameronraysmith/flytekit.git"
reference = "3928-pandas-2"
resolved_reference = "b1e64ba20f1ddd83723e455d2bf893d8f3fc84b7"
```

</p>
</details> 

### Conda Info

<details><summary>conda info</summary>
<p>

```shell
mamba version : 1.5.3
     active environment : base
    active env location : /usr/local/Caskroom/mambaforge/base
            shell level : 1
       user config file : /Users/user/.condarc
 populated config files : /usr/local/Caskroom/mambaforge/base/.condarc
                          /Users/user/.condarc
          conda version : 23.10.0
    conda-build version : not installed
         python version : 3.10.8.final.0
       virtual packages : __archspec=1=m1
                          __osx=13.6=0
                          __unix=0=0
       base environment : /usr/local/Caskroom/mambaforge/base  (writable)
      conda av data dir : /usr/local/Caskroom/mambaforge/base/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/bioconda/osx-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/nodefaults/osx-64
                          https://conda.anaconda.org/nodefaults/noarch
          package cache : /usr/local/Caskroom/mambaforge/base/pkgs
                          /Users/user/.conda/pkgs
       envs directories : /usr/local/Caskroom/mambaforge/base/envs
                          /Users/user/.conda/envs
               platform : osx-64
             user-agent : conda/23.10.0 requests/2.28.1 CPython/3.10.8 Darwin/22.6.0 OSX/13.6 solver/libmamba conda-libmamba-solver/23.11.0 libmambapy/1.5.3
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```

</p>
</details> 

### Conda Config

<details><summary>conda channels from pyproject.toml `tool.conda-lock` table</summary>
<p>

```shell
these are the channels specified in pyproject.toml

[tool.conda-lock]
channels = [
    'nodefaults', 
    'pytorch',
    'nvidia',
    'conda-forge', 
    'bioconda', 
]
```

</p>
</details> 

### Conda list

```shell
I'm not working in an environment. I'm just using conda-lock from a pipx installation to generate conda-lock and environment files.
```
