### ISSUE TITLE
Conda lock warns on missing name in

### ISSUE THREAD

**Issue by timhoffm** [conda/conda-lock#806]
### Checklist

- [x] I added a descriptive title
- [x] I searched open reports and couldn't find a duplicate

### What happened?

Using this `pyproject.toml`

```toml
[project]
name = "locktest"

requires-python = ">=3.11"

dependencies = [
    "scikit-learn",
    "scipy",
]


[tool.conda-lock]
channels = [
    "conda-forge",
]
```

I run `conda-lock lock -f pyproject.toml`

The output contains
```
WARNING:conda_lock.lookup:Could not find conda name for scikit-learn. Assuming identity.
WARNING:conda_lock.lookup:Could not find conda name for scipy. Assuming identity.
```

The assumption is correct. However, for such prominent packages I would not expect to see a warning.

### Additional Context

Running in debug mode confirms that this mapping file is downloaded:  https://raw.githubusercontent.com/regro/cf-graph-countyfair/master/mappings/pypi/grayskull_pypi_mapping.json

In there are no entries for scipy and scikit-learn, however there is e.g. a trivial entry for numpy. Should the above packages have trivial entries in there as well?
